version: "3"

services:
  bd-cashFlow:
    container_name: "bd-cashFlow"
    image: bitnami/mysql:8.0.35
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cashFlow
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_USER=user
      - MYSQL_PASSWORD=12345678
      - MYSQL_CLIENT_ENABLE_SSL=no
    ports:
      - 3306:3306
